/* PHASE_B_C_TODO: implement public header for kernel-alloc. */
#ifndef _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_KERNEL_ALLOC_H_
#define _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_KERNEL_ALLOC_H_

/* exported: init */
/* exported: transfer */

#endif /* _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_KERNEL_ALLOC_H_ */
