/* PHASE_B_C_TODO: implement public header for syscall. */
#ifndef _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_SYSCALL_H_
#define _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_SYSCALL_H_

/* exported: handle */

#endif /* _HOME_XU_HY22_GRADUATION_PHASE_C_CANDIDATE_TEMPLATE_C_PORT_INCLUDE_RCORE_SYSCALL_H_ */
